name: Publish to Roblox

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rojo via Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - run: aftman install
      - run: rojo build default.project.json -o place.rbxl

      - name: Publish place
        uses: boatbomber/publish-roblox-place@v1.1
        with:
          api-key: ${{ secrets.ROBLOX_API_KEY }}
          universe-id: ${{ secrets.ROBLOX_UNIVERSE_ID }}
          place-id: ${{ secrets.ROBLOX_PLACE_ID }}
          place-file: 'place.rbxl'
